import { PhoneFinderPage } from "@/components/phone-finder-page"

// Mock data for phone finder
const phoneDatabase = [
  {
    id: "samsung-galaxy-s24-ultra",
    name: "Samsung Galaxy S24 Ultra",
    brand: "Samsung",
    price: 1199,
    priceRange: "flagship",
    rating: 4.8,
    image: "/samsung-galaxy-s24-ultra.png",
    releaseDate: "2024-01-24",
    specs: {
      displaySize: 6.8,
      ram: 12,
      storage: 256,
      cameraMP: 200,
      batteryCapacity: 5000,
      processor: "Snapdragon 8 Gen 3",
      os: "Android",
      network: "5G",
      waterResistance: "IP68",
      weight: 232,
    },
    features: ["S Pen", "Wireless Charging", "Fast Charging", "Multiple Cameras", "AI Features"],
  },
  {
    id: "iphone-15-pro-max",
    name: "iPhone 15 Pro Max",
    brand: "Apple",
    price: 1099,
    priceRange: "flagship",
    rating: 4.9,
    image: "/iphone-15-pro-max.png",
    releaseDate: "2023-09-22",
    specs: {
      displaySize: 6.7,
      ram: 8,
      storage: 256,
      cameraMP: 48,
      batteryCapacity: 4441,
      processor: "A17 Pro",
      os: "iOS",
      network: "5G",
      waterResistance: "IP68",
      weight: 221,
    },
    features: ["Face ID", "Wireless Charging", "Fast Charging", "Multiple Cameras", "Action Button"],
  },
  {
    id: "google-pixel-8-pro",
    name: "Google Pixel 8 Pro",
    brand: "Google",
    price: 999,
    priceRange: "flagship",
    rating: 4.7,
    image: "/google-pixel-8-pro.png",
    releaseDate: "2023-10-12",
    specs: {
      displaySize: 6.7,
      ram: 12,
      storage: 128,
      cameraMP: 50,
      batteryCapacity: 5050,
      processor: "Google Tensor G3",
      os: "Android",
      network: "5G",
      waterResistance: "IP68",
      weight: 213,
    },
    features: ["AI Photography", "Wireless Charging", "Fast Charging", "Pure Android", "Magic Eraser"],
  },
  {
    id: "oneplus-12",
    name: "OnePlus 12",
    brand: "OnePlus",
    price: 799,
    priceRange: "premium",
    rating: 4.6,
    image: "/oneplus-12-product-shot.png",
    releaseDate: "2024-01-23",
    specs: {
      displaySize: 6.82,
      ram: 16,
      storage: 256,
      cameraMP: 50,
      batteryCapacity: 5400,
      processor: "Snapdragon 8 Gen 3",
      os: "Android",
      network: "5G",
      waterResistance: "IP65",
      weight: 220,
    },
    features: ["Fast Charging", "Wireless Charging", "Gaming Mode", "OxygenOS", "Alert Slider"],
  },
  {
    id: "xiaomi-14-ultra",
    name: "Xiaomi 14 Ultra",
    brand: "Xiaomi",
    price: 899,
    priceRange: "premium",
    rating: 4.5,
    image: "/xiaomi-14-ultra.png",
    releaseDate: "2024-02-25",
    specs: {
      displaySize: 6.73,
      ram: 16,
      storage: 512,
      cameraMP: 50,
      batteryCapacity: 5300,
      processor: "Snapdragon 8 Gen 3",
      os: "Android",
      network: "5G",
      waterResistance: "IP68",
      weight: 229,
    },
    features: ["Leica Cameras", "Fast Charging", "Wireless Charging", "MIUI", "Photography Pro"],
  },
  {
    id: "samsung-galaxy-a55",
    name: "Samsung Galaxy A55",
    brand: "Samsung",
    price: 449,
    priceRange: "mid-range",
    rating: 4.3,
    image: "/samsung-galaxy-a55.png",
    releaseDate: "2024-03-11",
    specs: {
      displaySize: 6.6,
      ram: 8,
      storage: 128,
      cameraMP: 50,
      batteryCapacity: 5000,
      processor: "Exynos 1480",
      os: "Android",
      network: "5G",
      waterResistance: "IP67",
      weight: 213,
    },
    features: ["Fast Charging", "Multiple Cameras", "One UI", "Expandable Storage"],
  },
]

export default function FinderPage() {
  return <PhoneFinderPage phoneDatabase={phoneDatabase} />
}
